#!/bin/bash

CACHE_DIR="${HOME}/.cache/iceterrain"
mkdir -p "${CACHE_DIR}"
pushd "${CACHE_DIR}"
for i in /usr/lib/iceterrain/* ; do
	basename="$(basename ${i})"
	if [ ! -f "${basename}" -a ! -L "${basename}" ]; then
		ln -s "${i}" . 2>/dev/null
	fi
done

if [ ! -f logging.properties ] ; then
	ln -sf /etc/iceterrain/logging.properties logging.properties
fi 
if [ $# = 0 ] ; then
	java -jar /usr/lib/iceterrain/getdown.jar .
else
	java -jar /usr/lib/iceterrain/getdown.jar . "" $@
fi 
